name: reusable workflow for Reactive Spring Book chapter code

env:

  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

  SPRING_PROFILES_ACTIVE: ci

  GH_PAT: ${{ secrets.GH_PAT }}
  
  PIPELINE_ORG_NAME: reactive-spring-book
  PIPELINE_REPO_NAME: pipeline
  
on:
  workflow_call:

jobs:

  build-and-publish:

    permissions:
      contents: 'read'
      id-token: 'write'

    name: Build and Publish 

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3

      - run: mkdir -p $HOME/.m2/ &&  cp .ci.settings.xml $HOME/.m2/settings.xml

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-            

      - uses: joshlong/java-version-export-github-action@v20

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          cache: 'maven'
          java-version: ${{ env.JAVA_MAJOR_VERSION }}

      - run: echo "using $JAVA_MAJOR_VERSION"

      - name: Build
        run: ls -la $GITHUB_WORKSPACE/.github/workflows/build.sh && $GITHUB_WORKSPACE/.github/workflows/build.sh || echo "no .github/workflows/build.sh found"
        
      - name: Maven 
        run: mvn -e -f $GITHUB_WORKSPACE/pom.xml verify deploy 

      - name: Initiate Pipeline
        run: |
          curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${GH_PAT}"  --request POST  \
              --data '{"event_type": "update-code-event" }' https://api.github.com/repos/${PIPELINE_ORG_NAME}/${PIPELINE_REPO_NAME}/dispatches
